### ISSUE TITLE
Build Status anchor and icon is referring to ureachable url

### ISSUE THREAD

**Issue by dropoutcoder** [dotnet/symstore#108]
In README.md build status info is referring to unreachable url(timeout error).

Windows
**x64 Debug**  https://ci.dot.net/job/dotnet_symstore/job/master/job/Windows_NT_Debug/
**x64 Release** https://ci.dot.net/job/dotnet_symstore/job/master/job/Windows_NT_Release/

Ubuntu 16.04
**Debug**  https://ci.dot.net/job/dotnet_symstore/job/master/job/Ubuntu16.04_Debug/
**Release** https://ci.dot.net/job/dotnet_symstore/job/master/job/Ubuntu16.04_Release/

Icon is not rendered and build status is not available.

**Comment by mikem8361** [comment]
I’m working on some engineering improvements, etc. to this repo and the build pipelines that should fix this.

**Comment by dropoutcoder** [comment]
That was quick. Everything look great now. Thanks.
