### ISSUE TITLE
Improve Symbol Uploader error reporting

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/symstore#139]
I've seen a few times the Symbol Uploader dump a large stack trace when it fails to communicate with the symbol server for some reason - i.e., when AzDO feed is flaky or some network problem happen. It would be good to capture this _common_ problem and present a more meaningful error message.

See sample problem here: https://dnceng.visualstudio.com/internal/_build/results?buildId=378145&view=results or https://github.com/aspnet/AspNetCore-Internal/issues/3202

@dougbu @mikem8361

**Comment by mikem8361** [comment]
New version 1.0.0-beta-64708-02. It is still being pushed to the buildtools myget feed. I still have some engineering to do to publish it to the dotnet-core blob feed. It is also on \bvtsrv2\team\DotNetCore\DotNet-SymUploader\20191108.02\packages\Shipping

**Comment by mikem8361** [comment]
See https://github.com/dotnet/symstore/issues/148

**Comment by JohnTortugo** [comment]
Thanks @mikem8361
