### ISSUE TITLE
Support .debug extension in ELFFileKeyGenerator

### ISSUE THREAD

**Issue by ww898** [dotnet/symstore#158]
Hi all,
what do you thing about handling a common Linux debug symbols extension `.debug` in additional to Microsoft specific `.dbg`? See https://github.com/dotnet/symstore/blob/72f83ecd6fa31573c864fc35be3ece3190bd3710/src/Microsoft.SymbolStore/KeyGenerators/ELFFileKeyGenerator.cs#L54

**Comment by k15tfu** [comment]
Faced with the same problem some time ago. The SymbolStoreKey for `*.debug` files was similar to the keys for regular modules `libfoo.so.debug/elf-buildid-e41e9416e02c47af8003882880a72e78b2a58a98/libfoo.so.debug`, but not for the symbols `_.debug/elf-buildid-sym-e41e9416e02c47af8003882880a72e78b2a58a98/_.debug`.

@mikem8361 I guess you are interested in fixing this, I can make a PR.

**Comment by mikem8361** [comment]
I just published a version 1.0.105301 of dotnet-symbol. 

This version of Microsoft.FileFormats or Microsoft.SymbolStore packages containing this fix is available on the https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json feed.
