### ISSUE TITLE
PE-timestamp-filesize format

### ISSUE THREAD

**Issue by DJm00n** [dotnet/symstore#220]
https://github.com/dotnet/symstore/blob/ccfa77ef0d395362d70a84404c24c8f30e81f039/docs/specs/SSQP_Key_Conventions.md#L15-L21

It's not clear if Timestamp should be extended to 8 chars with leading zeroes.

For example I have dll with [strange old timestamp](https://devblogs.microsoft.com/oldnewthing/20180103-00/?p=97705#:~:text=It's%20a%2032%2Dbit%20value,completely%20unrelated%20to%20any%20timestamp.):
![image](https://user-images.githubusercontent.com/1285934/94012623-b7a05c00-fdb1-11ea-93df-94f624a56b7a.png)

And for it path like`filename.dll/00E4915Eae000/filename.dll` is generated in MSVS request to symbol server.

But current `Microsoft.SymbolStore` implementation just generates PE file key without leading zeroes:
https://github.com/dotnet/symstore/blob/22c694a8c3217395c62ebaba523f2cc3dac775ba/src/Microsoft.SymbolStore/KeyGenerators/PEFileKeyGenerator.cs#L201

Seems like spec and code should be updated to match `DbgHelp.dll` implementation.

PS: https://randomascii.wordpress.com/2013/03/09/symbols-the-microsoft-way/ have note about that:
```
Note that the timeStamp is always printed as eight digits (with leading zeroes as needed) using upper-case for ‘A’ to ‘F’ (important if your symbol server is case sensitive), whereas the image size is printed using as few digits as needed, in lower-case.
```

**Comment by DJm00n** [comment]
I think code should be changed to:
```
string id = string.Format("{0:X8}{1:x}", timestamp, sizeOfImage); 
```

**Comment by tmat** [comment]
Note that when a module is build as reproducible the timestamp is not an actual time, but rather a content hash and hence could look odd when interpreted as time.

**Comment by mikem8361** [comment]
It looks like we did get the DLL timestamp formatting wrong. It has been that way from the beginning of the symstore repo.   I want to verify this in the Windows debugger code that builds DLL indexes (I think it is symsrv) to confirm this.  We probably have gotten away with it because the timestamp for the .NET Core DLLs seems to never have any leading zeros and our servers are case-insensitive.  Hopefully because of this, making this change doesn't break our current upload, download, SOS and other tool usage. 

Adding @noahfalk and @tommcdon.

**Comment by noahfalk** [comment]
Changing our spec to match what dbghelp actually does seems pretty reasonable to me. We were certainly trying to document existing behavior so that we would be interoperable rather than to define some new subtly different behavior.

**Comment by DJm00n** [comment]
Hi, @mikem8361! I saw that you already did a fix in your fork. Great! Any ETA when it could me merged to main and released as nuget package?

**Comment by DJm00n** [comment]
Seems `Microsoft.SymbolStore 1.0.147902` (built from f2731736d28ac7309a2da4ae036831049c6e1ad6) package already on NuGet feed. Thanks!

Closing.
