### ISSUE TITLE
Remove nuget.exe

### ISSUE THREAD

**Issue by richlander** [dotnet/symstore#26]
https://github.com/dotnet/symstore/blob/master/nuget.exe

Is this file needed? I thought that this need went away a long time ago, and it certainly doesn't work off of Windows.

This file is currently unattributed, so is violating our licensing policy. We could attribute it, but I'd prefer to just delete it.

/cc @tmat

**Comment by japj** [comment]
I think this can be closed, because nuget was removed as part of 7264cb93857da6d00692b965d45f00fef32d0106
