### ISSUE TITLE
Unable to download dotnet error

### ISSUE THREAD

**Issue by ShaneCourtrille** [dotnet/symstore#339]
I have a dump taken from a .NET Core 3.1 application and I'm executing the command **dotnet-symbol --host-only core_20220329_140711 dotnet** and I receive the following error:

```
Downloading from http://msdl.microsoft.com/download/symbols/
Writing: ./dotnet
ERROR: Not Found: dotnet - 'http://msdl.microsoft.com/download/symbols/apphost/elf-buildid-28c244c1953bcbee994709a4b849086ee7cf0c99/apphost'
```

The app is running with a Docker container using **mcr.microsoft.com/dotnet/core/aspnet:3.1.0-bionic** which appears to be out of date but would still be an official version so I'm not sure what the next step I would take to resolve this.

**Comment by mikem8361** [comment]
The ERROR message is misleading and should either be changed to a warning or not displayed (somehow) at all.  If you look at the output the line:
```
Writing: ./dotnet
```
This means you did download the host program needed for lldb.  It should be in the current directory.
