### ISSUE TITLE
Microsoft.SymbolStore NuGet Package

### ISSUE THREAD

**Issue by fowl2** [dotnet/symstore#343]
Is `Microsoft.SymbolStore` available via NuGet? I'd like to use it to download symbols programmatically. 

I found an [unlisted package](https://www.nuget.org/packages/JetBrains.Microsoft.SymbolStore), which seems to indicate I'm not the first :)

**Comment by mikem8361** [comment]
By publishing them to nuget would imply that we have the resources to fully support the Micrsoft.SymbolStore or Microsoft.FileFormats packages. We currently don't have the resources to support them. You are welcome to build and publish your own version like JetBrains or use symstore as a git sub-module in your repo.

**Comment by fowl2** [comment]
Fair enough, thanks for the response!

**Comment by fowl2** [comment]
@hoyosjs Did you mean to select "closed as not planned"?
![Screenshot showing dropdown menu containing issue close reasons](https://docs.github.com/assets/cb-14438/images/help/issues/close-issue-select-reason.png)

**Comment by hoyosjs** [comment]
Yes, sorry. Relatively new GitHub feature I'm still not in muscle memory familiarity with. Thanks for the callout.
