### ISSUE TITLE
Portable PDB age should be in lower case

### ISSUE THREAD

**Issue by ww898** [dotnet/symstore#49]
Should be `a.pdb/7ace356ee85544148c5aa8a96f2b8035ffffffff/a.pdb`  instead of `a.pdb/7ace356ee85544148c5aa8a96f2b8035FFFFFFFF/a.pdb` because https://github.com/dotnet/symstore/blob/master/docs/specs/SSQP_Key_Conventions.md.

**Comment by tmat** [comment]
I don't think the case matters as long as it's consistent.

**Comment by gregg-miskelly** [comment]
Does both symsrv.dll and Microsoft.FileFormats.dll generate them in upper case? If so, I think we should probably update the spec to match the implementation.

**Comment by mikem8361** [comment]
symsrv.dll doesn't currently handle portable PDBs as far as I know. But you are right, the spec should be changed to match Microsoft.FileFormats impl.

**Comment by gregg-miskelly** [comment]
symsrv.dll doesn't care what format of PDB it is dealing with. That is how VS downloads them.

**Comment by ww898** [comment]
https://github.com/dotnet/corefx/blob/master/src/System.Reflection.Metadata/specs/PE-COFF.md
> Version Major=any, Minor=0x504d of the data format has the same structure as above. The Age shall be 1. The format of the .pdb file that this PE/COFF file was built with is Portable PDB. The Major version specified in the entry indicates the version of the Portable PDB format. Together 16B of the Guid concatenated with 4B of the TimeDateStamp field of the entry form a PDB ID that should be used to match the PE/COFF image with the associated PDB (instead of Guid and Age). Matching PDB ID is stored in the #Pdb stream of the .pdb file.

**Comment by mikem8361** [comment]
In the symbol server index, Age = 1 means Windows (original) PDB and Age = 0xFFFFFFFF means Portable PDB.

**Comment by mikem8361** [comment]
I changed the spec to uppercase 0xFFFFFFFF for the Portable PDB index so it matches the implementations.

**Comment by ww898** [comment]
Well, why do you need `KeyTypeFlags.ForceWindowsPdbs` in that case? Should I use this flag or not? Should I generated both age variants: `1` and `0xFFFFFFFFF`?

**Comment by mikem8361** [comment]
The normal behavior for get symbol indexes from a PE/DLL is to return the portable PDB index (age=FFFFFFFF) if the debug directory in the DLL is marked as as such ("IsPortablePDB"), otherwise, the key generator returns the Windows PDB.  

When the ForceWindowsPDB flags is set, the key generator always returns the Windows PDB index (age=1). This is used when both the Windows and Portable PDBs are on the symbol server and the tool (legacy tools) or debugger (like Windbg or cdb) that only work with Windows PDBs.
(debuggers like WinDbg or cdb).
 (debuggers like WinDbg or cdb).

**Comment by ww898** [comment]
Please correct me if I am wrong. The WinDbg from WDK v10.0.16299 doesn't know anything about portable PDB in CodeView section of PE-file, so I need to have on my symbol server index with the age `1` if I want that the WinDbg (in fact symsrv.dll) download it. the WinDbg can't recognise the portable PDB format. However, sos.dll can work with it. New tools just use age `FFFFFFFF`. It means that if I don't know the user's tool I should use both ages on my server. Am I right?

**Comment by gregg-miskelly** [comment]
If you get a request with age=1, you should server the Windows PDB. If you get a request with age = `FFFFFFFF` you should server the portable PDB. If you only have a portable PDB, a request with age = 1 should return a file-not-found result (or you maybe you could convert them on the fly).
