### ISSUE TITLE
Symbol uploader shouldn't report warnings for unknown file extensions

### ISSUE THREAD

**Issue by tmat** [dotnet/symstore#76]
I’m getting some warnings from the build task:

         warning : Invalid file type: tools/bincore/RunCsc
         warning : Invalid file type: tools/bincore/RunVbc

these are bash scripts (with no extensions).

Packages may contain all sorts of files, the tool should silently skip files whose extension it doesn't recognize.

**Comment by mikem8361** [comment]
Done. Use version 1.0.0-beta-63412-03 of the uploader.
