### ISSUE TITLE
Error while publishing .so files: Invalid ELF BuildID '<null>'

### ISSUE THREAD

**Issue by tmat** [dotnet/symstore#81]
Tried to enable symbol publisher in dotnet/sourcelink repo again, now hitting the following error:

```
E:\A\_work\866\s\.packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.18616.5\tools\Publish.proj(131,5): error : Invalid ELF BuildID '<null>' for tools/netcoreapp2.0/runtimes/alpine-x64/native/libgit2-a904fc6.so
2018-12-18T18:19:49.9924832Z E:\A\_work\866\s\.packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.18616.5\tools\Publish.proj(131,5): error : Invalid ELF BuildID '<null>' for tools/netcoreapp2.0/runtimes/alpine-x64/native/libgit2-a904fc6.so
```

Repro by getting https://www.nuget.org/packages/LibGit2Sharp.NativeBinaries/1.0.258 package and publishing all files it contains.

**Comment by mikem8361** [comment]
This means that this ELF binary doesn’t have a build id.  The symbol uploader can create an index without so it considers it an error.  The fix is to change the libgit2 build to enable build ids.  This seems to vary a little across distros. Does the coreclr repo build this bin?

**Comment by tmat** [comment]
No, this is 3rd party library. We can ask them to enable build ids, but it seems we should be bale to skip files that don't have it.

**Comment by mikem8361** [comment]
I really don’t want to skip files on this error.  We would have missed that the FreeBSD coreclr binaries didn’t have build ids.

Why are we publishing 3rd party libraries?  That could be potentially dangerous publishing them to our Microsoft symbol servers.

**Comment by tmat** [comment]
I guess I should produce a separate symbol package that only includes our binaries and publish that instead. That seems like the best approach, right?

**Comment by mikem8361** [comment]
There is currently no way to exclude files in a package.  I could add a way but it would be a low priority feature. 

So yes, creating a separate symbol package with just our binaries would be a good way to fix this.

**Comment by tmat** [comment]
OK, I'll do that.
