### ISSUE TITLE
NugetSymbolServer sample instructions out of date

### ISSUE THREAD

**Issue by dagood** [dotnet/symstore#83]
Steps in [the sample NuGet symbol server readme](https://github.com/dotnet/symstore/blob/7bbc70933673d5c4e4720a70ba7f999f1a76dde5/src/NugetSymbolServer/README.md) don't work anymore. The project is a tool project now, and doesn't run with `dotnet run`, and simply changing the project type raises complaints about files not being copied to the `artifacts` dir.

I was trying to use it to stand up a quick symbol server to see if some non-online symbols would be matched up and used correctly against a snapshot, but wasn't able to make it work.

It also didn't seem to load some recent `runtime.win-x64.Microsoft.NETCore.App.<version>.symbols.nupkg` files that I stuck in a `nuget_feed` dir in artifacts, but that is probably another issue not worth looking at until some overall flow works.

**Comment by mikem8361** [comment]
This sample symbol server really isn't supported.  I really don't have the bandwidth to fix this.  Github also flagged a reference in this project as a security issue too (Microsoft.AspNetCore.Mvc).

Do you have sometime to fix up this project, update the reference and the README?

**Comment by dagood** [comment]
> Do you have sometime to fix up this project, update the reference and the README?

I don't. 🙁 IMO it would be nice to add a note (linking to this issue, maybe) or remove the parts of the doc that don't work, at least.

**Comment by mikem8361** [comment]
Fixed

**Comment by dagood** [comment]
Nice, thanks! 😄
