### ISSUE TITLE
dotnet symbol coredump doesn't work

### ISSUE THREAD

**Issue by Peperud** [dotnet/symstore#99]
In preparation for chasing a potential memory leak in an .NET Core MVC app (linux/docker), I'm trying to setup a linux environment for analyzing memory dumps.
Two machines - Ubuntu 16.04 & Ubuntu 18.04.
Both have .NET Core SDKs:
2.1.700
2.2.300

Tried to follow the instructions and getting stuck on the second step (`dotnet-symbol` gets installed without a problem). 
`dotnet symbol coredump` throws `No executable found matching command "dotnet-symbol"`. If I add `/home/<user>/.dotnet/tools` to the `$PATH`, the error changes to 
```bash
Downloading from http://msdl.microsoft.com/download/symbols/
ERROR: Input files not found
```
Doesn't seem to matter if I have a `global.json` local file, specifying .NET Core SDK 2.1

What am I missing?

**Comment by mikem8361** [comment]
Yes, that path needs to be added for global tools to be found.

Is “coredump” the name/path of your dump? It basically can find the core dump file.

mikem

**Comment by Peperud** [comment]
No, it wasn't. Thanks.
